param(
    [string]$Device = '192.168.1.35:5555',
    [string]$OutRoot = 'D:\carlinkit\DUDU_stock_opt\2609261951_2609241005\06_live_logs',
    [string]$Adb = 'adb'
)
$ErrorActionPreference='Stop'
$stamp=Get-Date -Format 'yyyyMMdd_HHmmss'; $OutDir=Join-Path $OutRoot "baseline_$stamp"
$dirs=@('identity','boot','kernel','services','packages','audio','bluetooth','cpaa','filesystem','maps','meta'); $dirs|%{New-Item -ItemType Directory -Force -Path (Join-Path $OutDir $_)|Out-Null}
$script:Step=0; $script:TotalSteps=40
function Invoke-AdbText { param([string[]]$AdbArgs,[string]$RelativePath); $script:Step++; Write-Host ("[{0:D2}/{1:D2}] {2}" -f $script:Step,$script:TotalSteps,$RelativePath); $dest=Join-Path $OutDir $RelativePath; try { $output=& $Adb @AdbArgs 2>&1; $output|Out-File $dest -Encoding utf8 -Width 4096 } catch { "ERROR: $($_.Exception.Message)"|Out-File $dest -Encoding utf8 } }
function Device-Adb { param([string[]]$DeviceArgs,[string]$RelativePath); Invoke-AdbText -AdbArgs (@('-s',$Device)+$DeviceArgs) -RelativePath $RelativePath }
function Shell { param([string]$Command,[string]$RelativePath); Device-Adb -DeviceArgs @('shell',$Command) -RelativePath $RelativePath }
Write-Host "Connecting to $Device ..."; & $Adb connect $Device|Out-Host; & $Adb -s $Device wait-for-device
$state=(& $Adb -s $Device get-state 2>&1|Out-String).Trim(); if($state-ne'device'){throw "ADB device state is '$state'"}; $idProbe=(& $Adb -s $Device shell id 2>&1|Out-String).Trim(); if($idProbe-notmatch'uid=0\(root\)'){throw "Root ADB shell required. Got: $idProbe"}
$state|Set-Content -Encoding UTF8 (Join-Path $OutDir 'meta\adb-state.txt'); $idProbe|Set-Content -Encoding UTF8 (Join-Path $OutDir 'identity\id.txt')
Shell 'date; uptime; uname -a; cat /proc/version' 'identity\system.txt'; Shell 'getprop' 'identity\getprop.txt'; Shell 'getenforce 2>&1; printf selinux_enforce=; cat /sys/fs/selinux/enforce 2>&1' 'identity\selinux.txt'; Shell 'getprop ro.build.fingerprint; getprop ro.build.version.incremental; getprop ro.build.version.release; getprop ro.build.version.sdk; getprop ro.vendor.build.version.sdk; getprop ro.product.first_api_level; getprop ro.build.version.security_patch; getprop ro.vendor.build.security_patch' 'identity\build-summary.txt'
Shell 'dmesg 2>&1' 'boot\dmesg.txt'; Device-Adb @('logcat','-d','-b','all','-v','threadtime') 'boot\logcat-all.txt'; Shell 'cat /proc/cmdline 2>&1; echo; cat /proc/bootconfig 2>&1' 'boot\cmdline-bootconfig.txt'
Shell 'cat /proc/modules 2>&1' 'kernel\proc-modules.txt'; Shell 'lsmod 2>&1' 'kernel\lsmod.txt'; Shell 'cat /proc/interrupts 2>&1' 'kernel\interrupts.txt'
Shell 'ps -A -o USER,PID,PPID,VSZ,RSS,WCHAN,ADDR,S,NAME,ARGS 2>&1 || ps -A -ef 2>&1' 'services\ps.txt'; Shell 'service list 2>&1' 'services\service-list.txt'; Shell 'lshal 2>&1' 'services\lshal.txt'; Shell 'dumpsys -l 2>&1' 'services\dumpsys-list.txt'; Shell "ps -A -ef 2>&1 | grep -Ei 'sd|car|reverse|mirror|bluetooth|sdsdk|audio|radio|ril|cnss'" 'services\oem-processes.txt'
Shell 'mount 2>&1' 'filesystem\mount.txt'; Shell 'cat /proc/mounts 2>&1' 'filesystem\proc-mounts.txt'; Shell 'df -h 2>&1' 'filesystem\df.txt'; Shell 'ls -l /dev/block/by-name 2>&1' 'filesystem\block-by-name.txt'; Shell 'cat /proc/partitions 2>&1' 'filesystem\partitions.txt'; Shell "for n in /dev/goc_serial /dev/carplaySvc_serial; do echo ===== `$n =====; ls -lZ `$n 2>&1; readlink -f `$n 2>&1; done; echo ===== related-dev-nodes =====; ls -lZ /dev 2>/dev/null | grep -Ei 'goc|tty|uart|bt|bluetooth|carplay'" 'filesystem\device-nodes.txt'
Shell 'pm list packages -f 2>&1' 'packages\packages-f.txt'; Shell "pm list packages 2>&1 | grep -Ei 'dudu|carsyso|suding|bluetooth|mirror|carplay|aibox|reverse|media'" 'packages\oem-packages.txt'; Shell "for p in com.carsyso.main com.carsyso.bluetooth com.carhomekit.mirror; do echo ===== `$p =====; pm path `$p 2>&1; dumpsys package `$p 2>/dev/null | grep -E 'versionName=|versionCode=|codePath=|primaryCpuAbi=|secondaryCpuAbi=|nativeLibraryDir='; done" 'packages\oem-package-details.txt'
Shell 'dumpsys audio 2>&1' 'audio\dumpsys-audio.txt'; Shell 'dumpsys media.audio_flinger 2>&1' 'audio\audio-flinger.txt'; Shell 'dumpsys media.audio_policy 2>&1' 'audio\audio-policy.txt'; Shell 'tinymix 2>&1' 'audio\tinymix-passive.txt'; Shell 'cat /proc/asound/cards 2>&1; echo; cat /proc/asound/pcm 2>&1; echo; cat /proc/asound/devices 2>&1' 'audio\proc-asound.txt'; Shell 'for f in /proc/asound/card*/pcm*/sub*/status /proc/asound/card*/pcm*/sub*/hw_params; do [ -r $f ] && { echo ===== $f =====; cat $f; }; done' 'audio\pcm-state.txt'; Shell "find /vendor/etc /odm/etc -maxdepth 3 -type f 2>/dev/null | grep -Ei 'audio|mixer|sound' | sort" 'audio\config-paths.txt'
Shell 'dumpsys bluetooth_manager 2>&1' 'bluetooth\bluetooth-manager.txt'; Shell "getprop | grep -Ei 'bluetooth|bt\.|sdsdk|goc'" 'bluetooth\properties.txt'; Shell "ps -A -ef 2>&1 | grep -Ei 'bluetooth|sdsdk|carsyso|suding|goc'" 'bluetooth\processes.txt'; Shell "ps -A -ef 2>&1 | grep -Ei 'sdAutoReverse|sdCarplaySvc|sd_carplay|carsyso|suding|reverse|carplay|mirror|ght-play'" 'cpaa\processes.txt'; Shell "getprop | grep -Ei 'carplay|androidauto|reverse|mirror|aibox|sd\.'" 'cpaa\properties.txt'
$pidCommand="ps -A -o PID,ARGS | awk 'NR > 1 && `$2 ~ /^(sdAutoReverse|sdCarplaySvc|sdCarplaySvc_wire|sd_carplay|sd_mdnsd|sd_mdnsd_wire|sdsdk816|audioserver|android.hardware.audio.service|android.hardware.bluetooth@1.0-service-qti|com.android.bluetooth|com.carsyso.main|com.carsyso.bluetooth|com.carhomekit.mirror|com.suding.speedplay(:daemon)?|ght-play)$/ {print `$1}'"
Shell $pidCommand 'maps\pid-inventory.txt'
$pidFile=Join-Path $OutDir 'maps\pid-inventory.txt'; $pidText=Get-Content -Raw -ErrorAction SilentlyContinue $pidFile
if($pidText -match 'syntax error|inaccessible or not found|not found'){ throw "PID inventory command failed. See $pidFile" }
$matchedPids=@($pidText -split '\s+' | Where-Object { $_ -match '^\d+$' } | Select-Object -Unique)
if($matchedPids.Count -eq 0){ throw "PID inventory returned no relevant processes. See $pidFile" }
$runtimeDest=Join-Path $OutDir 'maps\relevant-process-runtime.txt'; "matched_pids=$($matchedPids -join ',')" | Set-Content $runtimeDest -Encoding utf8
# $PID is a built-in read-only PowerShell automatic variable, so never use $pid as a loop variable.
foreach($processId in $matchedPids){ Write-Host "    [proc] PID $processId"; $cmd="echo ===== PID $processId =====; printf 'cmdline: '; tr '\000' ' ' < /proc/$processId/cmdline 2>&1; echo; printf 'exe: '; readlink /proc/$processId/exe 2>&1; echo --maps--; cat /proc/$processId/maps 2>&1; echo --fds--; ls -lZ /proc/$processId/fd 2>&1"; (& $Adb -s $Device shell $cmd 2>&1) | Add-Content $runtimeDest -Encoding utf8 }
Shell 'ls -lt /data/tombstones 2>&1 | head -40' 'boot\tombstones.txt'
$probe=Get-Content -Raw -ErrorAction SilentlyContinue (Join-Path $OutDir 'identity\getprop.txt'); if(-not $probe -or $probe-notmatch'\[ro\.'){throw "Collection validation failed: invalid getprop output: $OutDir"}
$runtimeProbe=Get-Content -Raw -ErrorAction SilentlyContinue $runtimeDest; if($runtimeProbe -match 'syntax error'){throw "Runtime /proc capture contains shell syntax error: $runtimeDest"}; if($runtimeProbe-notmatch'===== PID'){throw "Runtime /proc capture has no PID sections: $runtimeDest"}
@("device=$Device","collected=$(Get-Date -Format o)","output=$OutDir","adb_state=$state","shell_id=$idProbe","matched_pids=$($matchedPids -join ',')",'validation=passed','runtime_proc_capture=passed','mode=read-only runtime baseline; no su/setprop/remount/kill/restart/tinymix writes')|Set-Content -Encoding UTF8 (Join-Path $OutDir 'meta\README.txt'); Write-Host ''; Write-Host 'Baseline collection complete and validation passed.'; Write-Host "Matched runtime PIDs: $($matchedPids -join ', ')"; Write-Host "Output: $OutDir"
